# Generated by Django 5.1.1 on 2024-10-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divino_pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantite',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='tailles',
            field=models.CharField(max_length=100),
        ),
    ]
