# Generated by Django 5.1.1 on 2024-11-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divino_pos', '0002_remove_transaction_mode_paiement_paymentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('cash', 'Espèces'), ('card', 'Carte bancaire'), ('gift', 'Chèque cadeau')], help_text='Méthode de paiement utilisée pour la transaction.', max_length=50, null=True),
        ),
    ]
