# Generated by Django 5.1.1 on 2024-10-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divino_pos', '0003_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fidelity_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
