# Generated by Django 5.1.1 on 2024-11-21 12:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divino_pos', '0003_transaction_mode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='global_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant de la réduction globale', max_digits=5),
        ),
    ]
