# Generated by Django 5.1.1 on 2024-11-22 10:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divino_pos', '0004_transaction_global_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
