# Generated by Django 5.1.1 on 2024-10-15 08:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divino_pos', '0005_alter_purchase_options_purchase_montant_reduction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['nom_article'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-date'], 'verbose_name': 'Achat', 'verbose_name_plural': 'Achats'},
        ),
        migrations.AlterField(
            model_name='client',
            name='code_postal',
            field=models.CharField(help_text='Code postal du client.', max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_anniversaire',
            field=models.DateField(blank=True, help_text="Date d'anniversaire du client.", null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(help_text='Adresse email unique du client.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='fidelity_points',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Points de fidélité accumulés par le client.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='client',
            name='n_carte',
            field=models.CharField(help_text='Numéro de carte unique pour chaque client.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(help_text='Nom de famille du client.', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='numero_rue',
            field=models.CharField(help_text='Numéro et nom de rue du client.', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='pays',
            field=models.CharField(help_text='Pays du client.', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(help_text='Prénom du client.', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(help_text='Numéro de téléphone du client.', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='ville',
            field=models.CharField(help_text='Ville du client.', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='categorie',
            field=models.CharField(help_text='Catégorie à laquelle appartient le produit.', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='code_article',
            field=models.CharField(help_text='Code article unique pour chaque produit.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code_ean',
            field=models.CharField(help_text='Code EAN à 13 chiffres unique pour chaque produit.', max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='couleurs',
            field=models.CharField(help_text='Couleurs disponibles pour le produit.', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='nom_article',
            field=models.CharField(help_text="Nom complet de l'article.", max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, help_text="Prix d'achat de l'article.", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='prix_vente',
            field=models.DecimalField(decimal_places=2, help_text="Prix de vente de l'article.", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantite',
            field=models.PositiveIntegerField(help_text='Quantité en stock du produit.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='tailles',
            field=models.CharField(help_text='Tailles disponibles pour le produit.', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='client',
            field=models.ForeignKey(help_text="Client ayant effectué l'achat.", on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='divino_pos.client'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Date et heure de l'achat."),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='montant_reduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant de la réduction appliquée sur cet achat.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(help_text='Produit acheté.', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='divino_pos.product'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantité achetée.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text="Prix total de l'achat après réduction.", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
