# Generated by Django 5.1.1 on 2024-11-22 11:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divino_pos', '0005_transactionitem_original_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='global_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pourcentage de réduction globale appliquée.', max_digits=5),
        ),
    ]
