# Generated by Django 5.1.1 on 2024-12-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divino_pos', '0006_alter_transaction_global_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('cash', 'Espèces'), ('card', 'Carte bancaire'), ('gift', 'Chèque cadeau'), ('Bon cadeau', 'Bon cadeau'), ('Virement', 'Virement'), ('Crédit', 'Crédit')], help_text='Méthode de paiement utilisée pour la transaction.', max_length=50, null=True),
        ),
    ]
