# Generated by Django 5.1.1 on 2024-10-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divino_pos', '0008_alter_purchase_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={},
        ),
    ]
