# Generated by Django 5.1.1 on 2024-10-16 12:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divino_pos', '0011_alter_purchase_client_alter_purchase_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total_reduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
