# Generated by Django 5.1.1 on 2024-10-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divino_pos', '0013_transaction_transactionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(help_text='Numéro', max_length=20),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
