# Generated by Django 5.1.1 on 2024-10-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divino_pos', '0014_alter_client_telephone_delete_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mode_paiement',
            field=models.CharField(choices=[('carte', 'Carte Bancaire'), ('especes', 'Espèces')], default='especes', max_length=10),
        ),
    ]
