# Generated by Django 5.1.1 on 2024-10-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divino_pos', '0016_alter_transaction_mode_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='mode_paiement',
            field=models.CharField(choices=[('carte', 'Carte Bancaire'), ('cash', 'Cash')], max_length=20),
        ),
    ]
