# Generated by Django 5.1.1 on 2024-10-17 15:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divino_pos', '0019_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='points_gagnes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
