# Generated by Django 5.1.1 on 2024-10-18 09:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divino_pos', '0020_transaction_points_gagnes'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Crédit disponible pour le client après retour d'articles.", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
