# Generated by Django 5.1.1 on 2024-10-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divino_pos', '0024_transaction_credit_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
