# Generated by Django 5.1.1 on 2024-10-20 07:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divino_pos', '0025_transactionitem_is_returned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterModelOptions(
            name='return',
            options={'verbose_name': 'Retour', 'verbose_name_plural': 'Retours'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='transactionitem',
            options={'verbose_name': 'Article de Transaction', 'verbose_name_plural': 'Articles de Transaction'},
        ),
        migrations.AlterModelOptions(
            name='voucher',
            options={'verbose_name': "Bon d'Achat", 'verbose_name_plural': "Bons d'Achat"},
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantité déjà retournée pour cet article.'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(help_text='Numéro de téléphone du client.', max_length=20),
        ),
        migrations.AlterField(
            model_name='return',
            name='points_removed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Points retirés lors du retour.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='return',
            name='transaction_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='divino_pos.transactionitem'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='divino_pos.client'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='points_gagnes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Points gagnés lors de cette transaction.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='is_returned',
            field=models.BooleanField(default=False, help_text="Indique si l'article a été entièrement retourné."),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='points_gagnes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Points gagnés sur cet article.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='divino_pos.client'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(help_text='Code unique du bon.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='valid_until',
            field=models.DateTimeField(help_text="Date d'expiration du bon."),
        ),
    ]
