# Generated by Django 5.1.1 on 2024-10-26 15:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divino_pos', '0026_alter_product_options_alter_return_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionitem',
            name='is_returned',
        ),
        migrations.AlterField(
            model_name='client',
            name='code_postal',
            field=models.CharField(blank=True, help_text='Code postal du client.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='numero_rue',
            field=models.CharField(blank=True, help_text='Numéro et nom de rue du client.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='pays',
            field=models.CharField(blank=True, help_text='Pays du client.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, help_text='Numéro de téléphone du client.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ville',
            field=models.CharField(blank=True, help_text='Ville du client.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='categorie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='couleurs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tailles',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='return',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant remboursé au client pour ce retour.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credit_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant du crédit appliqué à cette transaction.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mode_paiement',
            field=models.CharField(choices=[('carte', 'Carte Bancaire'), ('cash', 'Espèces')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='points_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant des points de fidélité appliqués à cette transaction.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Montant total de la transaction après réductions et applications des crédits/points.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_reduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total des réductions appliquées.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text="Prix unitaire de l'article.", max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='reduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Réduction unitaire appliquée à l'article.", max_digits=10),
        ),
    ]
