# Generated by Django 5.1.1 on 2024-10-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divino_pos', '0027_remove_transactionitem_is_returned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='promotion_applied',
            field=models.BooleanField(default=False, help_text='Indique si une promotion a été appliquée sur cet article.'),
        ),
    ]
