# Generated by Django 5.1.1 on 2024-10-27 12:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divino_pos', '0028_transactionitem_promotion_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
