# Generated by Django 5.1.1 on 2024-10-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divino_pos', '0029_alter_product_prix_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_article',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
