# Generated by Django 5.1.1 on 2024-11-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divino_pos', '0030_alter_product_code_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, help_text='Adresse email du client.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='n_carte',
            field=models.CharField(blank=True, help_text='Numéro de carte unique pour chaque client.', max_length=100, null=True, unique=True),
        ),
    ]
