# Generated by Django 5.1.1 on 2024-11-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divino_pos', '0031_alter_client_email_alter_client_n_carte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_ean',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
