# Generated by Django 5.1.1 on 2024-11-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divino_pos', '0032_alter_product_code_ean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='n_carte',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
